title: cc
author: carolina
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  documenting learning path && archiving resources

# social links
github_username:  carolinaferraz

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
